class Database:
    def __init__(self):
        self.books = [
            {"title": "1984", "author": "George Orwell", "year": 1949},
            {"title": "The Hobbit", "author": "J.R.R. Tolkien", "year": 1937},
            {"title": "Pride and Prejudice", "author": "Jane Austen", "year": 1813},
            {"title": "To Kill a Mockingbird", "author": "Harper Lee", "year": 1960},
            {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "year": 1925},
            {"title": "One Hundred Years of Solitude", "author": "Gabriel García Márquez", "year": 1967},
            {"title": "In Search of Lost Time", "author": "Marcel Proust", "year": 1913},
            {"title": "Moby-Dick", "author": "Herman Melville", "year": 1851},
            {"title": "War and Peace", "author": "Leo Tolstoy", "year": 1869},
            {"title": "Hamlet", "author": "William Shakespeare", "year": 1603},
            {"title": "The Catcher in the Rye", "author": "J.D. Salinger", "year": 1951},
            {"title": "The Lord of the Rings", "author": "J.R.R. Tolkien", "year": 1954},
            {"title": "Great Expectations", "author": "Charles Dickens", "year": 1861},
            {"title": "Ulysses", "author": "James Joyce", "year": 1922},
            {"title": "The Brothers Karamazov", "author": "Fyodor Dostoevsky", "year": 1880},
            {"title": "Crime and Punishment", "author": "Fyodor Dostoevsky", "year": 1866},
            {"title": "Anna Karenina", "author": "Leo Tolstoy", "year": 1877},
            {"title": "The Adventures of Huckleberry Finn", "author": "Mark Twain", "year": 1884},
            {"title": "Alice's Adventures in Wonderland", "author": "Lewis Carroll", "year": 1865},
            {"title": "Madame Bovary", "author": "Gustave Flaubert", "year": 1857},
            {"title": "Beloved", "author": "Toni Morrison", "year": 1987},
            {"title": "The Road", "author": "Cormac McCarthy", "year": 2006},
            {"title": "Life of Pi", "author": "Yann Martel", "year": 2001},
            {"title": "The Book Thief", "author": "Markus Zusak", "year": 2005},
            {"title": "The Goldfinch", "author": "Donna Tartt", "year": 2013},
            {"title": "Never Let Me Go", "author": "Kazuo Ishiguro", "year": 2005},
            {"title": "The Catcher in the Rye", "author": "J.D. Salinger", "year": 1951},
            {"title": "1984", "author": "George Orwell", "year": 1949},
            {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "year": 1925},
            {"title": "Brave New World", "author": "Aldous Huxley", "year": 1932},
            {"title": "Fahrenheit 451", "author": "Ray Bradbury", "year": 1953},
            {"title": "Animal Farm", "author": "George Orwell", "year": 1945},
            {"title": "Jane Eyre", "author": "Charlotte Brontë", "year": 1847},
            {"title": "Wuthering Heights", "author": "Emily Brontë", "year": 1847},
            {"title": "Pride and Prejudice", "author": "Jane Austen", "year": 1813},
            {"title": "Frankenstein", "author": "Mary Shelley", "year": 1818},
            {"title": "Dracula", "author": "Bram Stoker", "year": 1897},
            {"title": "The Picture of Dorian Gray", "author": "Oscar Wilde", "year": 1890},
            {"title": "The Brothers Karamazov", "author": "Fyodor Dostoevsky", "year": 1880},
            {"title": "Crime and Punishment", "author": "Fyodor Dostoevsky", "year": 1866},
            {"title": "The Metamorphosis", "author": "Franz Kafka", "year": 1915},
            {"title": "The Trial", "author": "Franz Kafka", "year": 1925},
            {"title": "Slaughterhouse-Five", "author": "Kurt Vonnegut", "year": 1969},
            {"title": "Catch-22", "author": "Joseph Heller", "year": 1961},
            {"title": "American Gods", "author": "Neil Gaiman", "year": 2001},
            {"title": "A Game of Thrones", "author": "George R.R. Martin", "year": 1996},
            {"title": "Cloud Atlas", "author": "David Mitchell", "year": 2004},
            {"title": "The Shadow of the Wind", "author": "Carlos Ruiz Zafón", "year": 2001},
            {"title": "The Night Circus", "author": "Erin Morgenstern", "year": 2011},
            {"title": "The Alchemist", "author": "Paulo Coelho", "year": 1988},
            {"title": "The Da Vinci Code", "author": "Dan Brown", "year": 2003},
            {"title": "The Kite Runner", "author": "Khaled Hosseini", "year": 2003},
            {"title": "Shantaram", "author": "Gregory David Roberts", "year": 2003},
            {"title": "Norwegian Wood", "author": "Haruki Murakami", "year": 1987},
            {"title": "1Q84", "author": "Haruki Murakami", "year": 2009},
            {"title": "The Wind-Up Bird Chronicle", "author": "Haruki Murakami", "year": 1994},
            {"title": "Invisible Man", "author": "Ralph Ellison", "year": 1952},
            {"title": "Gone with the Wind", "author": "Margaret Mitchell", "year": 1936},
            {"title": "Rebecca", "author": "Daphne du Maurier", "year": 1938},
            {"title": "Lolita", "author": "Vladimir Nabokov", "year": 1955},
            {"title": "The Master and Margarita", "author": "Mikhail Bulgakov", "year": 1967},
            {"title": "The Sun Also Rises", "author": "Ernest Hemingway", "year": 1926},
            {"title": "A Farewell to Arms", "author": "Ernest Hemingway", "year": 1929},
            {"title": "The Old Man and the Sea", "author": "Ernest Hemingway", "year": 1952},
            {"title": "The Bell Jar", "author": "Sylvia Plath", "year": 1963},
            {"title": "On the Road", "author": "Jack Kerouac", "year": 1957},
            {"title": "The Grapes of Wrath", "author": "John Steinbeck", "year": 1939},
            {"title": "East of Eden", "author": "John Steinbeck", "year": 1952},
            {"title": "Of Mice and Men", "author": "John Steinbeck", "year": 1937},
            {"title": "The Pearl", "author": "John Steinbeck", "year": 1947}
        ]

    def add_book(self, title, author, year):
        self.books.append({"title": title, "author": author, "year": year})

    def get_books(self):
        return self.books